pipeline {
    agent any

    stages {
        stage('FicheroSalida') {
            steps {
                echo 'Calculadora'
                script{
                   
                    
                    def data = readFile(file: "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Ejercicio15\\salida.txt")  
                    
                    println "$data"
                    
                    
                    
                    
                }
                
            }
        }
        
    }
}
